[book]
title = "Bonfire"
authors = ["Kat"]
language = "en"
src = "src"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/northernpaws/bonfire"
edit-url-template = "https://github.com/northernpaws/bonfire/main/book/{path}"
playground.runnable = false
additional-css = ["mdbook-protobuf.css"]

[preprocessor]

[preprocessor.protobuf]
command = "mdbook-protobuf"
proto_descriptor = "./descriptor_set.pb"
# nest_under = "API Reference" # if you want to have the proto reference placed as a child of a page - set that page name here.
# proto_url_root = "https://github.com/northernpaws/bonfire/tree/main/src/proto" # remove this if you don't have a source to link to
