[book]
title = "Bonfire"
authors = ["Kat"]
language = "en"
src = "src"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/northernpaws/bonfire"
edit-url-template = "https://github.com/northernpaws/bonfire/main/book/{path}"
playground.runnable = false
additional-css = ["mdbook-protobuf.css"]
